#!/usr/bin/env node

const fs         = require("fs");
const marked     = require("marked");
const _          = require("lodash");
const makeConfig = require("../lib/config.js");
const {
  parseAct,
  caseSplitAct,
  newCleanup,
  makeInterabiExhaustiveness
}                = require("../lib/build.js");
const {
  read,
  revert,
  testPath,
}                = require("../lib/util.js");

const __a2n = act => act.subject + "_" + act.name;

const KLAB_OUT = process.env.KLAB_OUT || "out";

const usage = `
Usage:
  klab make
`

if (!testPath("./config.json")) {revert("No config.json file in directory. Review `klab/examples` folder for inspiration")}
const config_json   = JSON.parse(fs.readFileSync("./config.json"));
const config        = makeConfig(config_json);
const config_path   = config.src.specification;
const raw_md_config = Array.isArray(config_path) && config_path.map(p => read(p)).join("\n\n") || read(config_path)

const tokens        = marked.lexer(raw_md_config)
const parsed_tokens = tokens
  .map(t => {
    if(t.type === 'code' && t.lang === "act") {
      const parsedAct = parseAct(config)(t.text, true);
      const cases = caseSplitAct(config)(parsedAct);
      return {
        type: 'code',
        lang: "act",
        obj: parsedAct,
        cases: cases,
        text: newCleanup(parsedAct, t.text)
      };
    } else {
      return t;
    }
  });

const act_collection = parsed_tokens
  .filter(e => e.type === "code" && e.lang === "act")
  .map(e => e.cases)
  .reduce((a, cs) => a.concat(cs), [])

var exhaustiveness_set = new Set()
for (var act_num in act_collection) {
  exhaustiveness_set.add(act_collection[act_num].act.subject + '__exhaustiveness')
}
const exhaustiveness = [...exhaustiveness_set]

const dependencies = Object.assign({},
  ...act_collection
  .map((a) => ({ [a.name]: (a.act.calls || []).map(d => d.replace('.', '_') + '_pass') })))

output_makefile = []
fail_rough = []
pass_rough = []
pass = []
for (var dep_name in dependencies) {
  let dep_name_without_rough = dep_name.substring(0, dep_name.length - 6)
  let dep_subtargets         = dependencies[dep_name]
  let isPass                 = dep_name.endsWith('_pass_rough') || dep_name.endsWith('_pass')
  let isRough                = dep_name.endsWith('_rough')
  let subtarget_string       = dep_subtargets.map(d => '$(KLAB_OUT_LOCAL)/accept/' + d).join(' ')
  output_makefile.push('$(KLAB_OUT_LOCAL)/built/' + dep_name + ': ' + subtarget_string + ' $(SPEC_SRCS)')
  output_makefile.push('\t$(BUILD) ' + dep_name)
  output_makefile.push('\t@mkdir -p $(dir $@)')
  output_makefile.push('\t@touch $@')
  output_makefile.push('')
  if (isPass) {
    pass.push(dep_name_without_rough)
    if (isRough) {
      pass_rough.push(dep_name)
    }
  } else {
    fail_rough.push(dep_name)
  }
}
output_makefile.push('$(KLAB_OUT_LOCAL)/accept/%__exhaustiveness: $(KLAB_OUT_LOCAL)/built/%__exhaustiveness')
output_makefile.push('\t$(PROVE) $*__exhaustiveness')
output_makefile.push('\t@mkdir -p $(dir $@)')
output_makefile.push('\t@touch $@')
output_makefile.push('')
output_makefile.push('$(KLAB_OUT_LOCAL)/accept/%_pass_rough: $(KLAB_OUT_LOCAL)/built/%_pass_rough')
output_makefile.push('\t$(PROVE_DUMP) $*_pass_rough')
output_makefile.push('\t@mkdir -p $(dir $@)')
output_makefile.push('\t@touch $@')
output_makefile.push('')
output_makefile.push('$(KLAB_OUT_LOCAL)/accept/%_pass: $(KLAB_OUT_LOCAL)/built/%_pass')
output_makefile.push('\t$(PROVE) $*_pass')
output_makefile.push('\t@mkdir -p $(dir $@)')
output_makefile.push('\t@touch $@')
output_makefile.push('')
output_makefile.push('$(KLAB_OUT_LOCAL)/accept/%_fail_rough: $(KLAB_OUT_LOCAL)/built/%_fail_rough')
output_makefile.push('\t$(PROVE) $*_fail_rough')
output_makefile.push('\t@mkdir -p $(dir $@)')
output_makefile.push('\t@touch $@')
output_makefile.push('')
output_makefile.push('$(KLAB_OUT_LOCAL)/built/%__exhaustiveness: $(SPEC_SRCS)')
output_makefile.push('\t$(BUILD) $*__exhaustiveness')
output_makefile.push('\t@mkdir -p $(dir $@)')
output_makefile.push('\t@touch $@')
output_makefile.push('')
output_makefile.push('$(KLAB_OUT_LOCAL)/built/%_pass: $(KLAB_OUT_LOCAL)/gas/%_pass_rough')
output_makefile.push('\t$(BUILD) $*_pass')
output_makefile.push('\t@mkdir -p $(dir $@)')
output_makefile.push('\t@touch $@')
output_makefile.push('')
output_makefile.push('$(KLAB_OUT_LOCAL)/gas/%_pass_rough: $(KLAB_OUT_LOCAL)/accept/%_pass_rough $(SPEC_SRCS)')
output_makefile.push('\t$(GET_GAS) $*_pass_rough')
output_makefile.push('\t$(SOLVE_GAS) $*_pass_rough')
output_makefile.push('\t@mkdir -p $(dir $@)')
output_makefile.push('\t@touch $@')
output_makefile.push('')
output_makefile.push('exhaustiveness_specs := ' + exhaustiveness.join(' \\\n                        '))
output_makefile.push('')
output_makefile.push('pass_rough_specs     := ' + pass_rough.join(' \\\n                        '))
output_makefile.push('')
output_makefile.push('pass_specs           := ' + pass.join(' \\\n                        '))
output_makefile.push('')
output_makefile.push('fail_rough_specs     := ' + fail_rough.join(' \\\n                        '))
output_makefile.push('')
output_makefile.push('all_specs            := $(exhaustiveness_specs) $(pass_rough_specs) $(pass_specs) $(fail_rough_specs)')
output_makefile.push('')
output_makefile.push('prove: $(patsubst %, $(KLAB_OUT_LOCAL)/accept/%, $(all_specs))')
output_makefile.push('')
output_makefile.push('.SECONDARY: $(patsubst %, $(KLAB_OUT_LOCAL)/built/%, $(all_specs))  \')
output_makefile.push('            $(patsubst %, $(KLAB_OUT_LOCAL)/accept/%, $(all_specs)) \')
output_makefile.push('            $(patsubst %, $(KLAB_OUT_LOCAL)/gas/%, $(all_specs))')
output_makefile.push('')

console.log(output_makefile.join('\n'))
